 const data = [
     { id: 1, name: "Iron Man", power: "Intelligence, The suit", content: "Genius. Billionaire. Philanthropist. Tony Stark's confidence is only matched by his high-flying abilities as the hero called Iron Man. Howard and Maria Stark were billionaire weapon manufacturers who wanted to have a child. They tried to make one themselves, but due to problems Maria was facing the baby was doomed to die. To save the child, Howard desperately used his immense wealth to search across the world for a cure to the child's illness. In his travels he ended up saving an alien known as Rigellian Recorder 451. Recorder saw potential in Earth's future but also feared it would be crushed by other, more advanced races. To give Earth a fighting chance and thank Howard for his troubles, Recorder offered to genetically engineer the unborn baby for Howard and Maria to give him the intellectual power needed to bring the world to a new age of technology. Howard graciously accepted, and Arno Stark was born after a five month procedure. Unfortunately, Arno's health quickly degenerated to the point where he'd need medical help to survive for the rest of his life. Because his condition was so poor, Howard and Maria just decided to adopt the young Anthony Edward Stark." , image: "/ironman.jpg"},
     { id: 2, name: "Captain Marvel", power: "FlightEnergy BlastsSuperhuman DurabilitySuperhuman Strength", content: "When head of NASA security Carol Danvers was exposed to a powerful alien device, she transformed into the mighty cosmic powered hero, Captain Marvel! Carol Danvers entered the Air Force upon graduating from high school to pursue her love of aircrafts and her dreams of flying. Carol was a top student at the Air Force Academy and enjoyed a rapid career advancement rising to the rank of Major. Because of her stellar performance, superb combat skills and natural intellect, Carol was recruited into the intelligence field. She ended up serving with the C.I.A., during which time she met and worked with Colonel Nick Fury. She was partnered with Colonel Michael Rossi and the two became lovers. Carol had a distinguished career in the C.I.A. While on special assignment with Nick Fury, Carol met the Canadian agent called Logan. The two were eventually paired up and shared a number of adventures together. During one of their infamous escapades, they clashed with the brutal Sabretooth who was working for the Hellfire Club. During their time together, Logan and Carol became close friends, perhaps even lovers. Both have saved each other’s lives numerous times.", image: "/captin_marvel.jpg"},
     { id: 3, name: "Captain America", power: "Enhanced strength, speed, stamina, durability", content: "Recipient of the Super Soldier serum, World War II hero Steve Rogers fights for American ideals as one of the world’s mightiest heroes and the leader of the Avengers. Captain America is probably the greatest human leader, hand-to-hand fighter, hero and inspirational figure in the Marvel Universe. He’s often been the leader of the Avengers. Though bad writing occasionally got in the way, Cap is often considered a reliable ethical and moral compass – he always does the right thing.", image: "/captin_america.jpg"},
     { id: 4, name: "Thor", power: "summon rain, wind, lightning, and thunder", content: "Born as the half-Asgardian, half-Elder God son of Odin, the All-Father and King of Asgard, and as the Norse God of Thunder, Thor was an adventurous yet ill-tempered deity, often travelling to other realms to do battle with Asgard’s foes. He spent much of his time in Midgard in particular, or our Earth, fighting as the mythic Germanic hero Siegfried and battling the ancient mutant, Apocalypse. As he became more arrogant, it became apparent to Odin that his son needed to learn the value of humility. To do so, he stripped Thor of his powers and memories, rendering him human and stranding him on Earth.", image: "/thor.jpg"},
     { id: 5, name: "Hulk", power: "Incredible superhuman strength, durability, and healing factor", content: "The Hulk is one of the strongest beings ever. ... The Hulk's super strength also allows him to run at great speed (with a limit) and leap exceptionally long distances, almost as if he were flying. When slamming his hands together, he can also create destructive shockwaves. For his size, the Hulk is incredibly fast and can run great distances at extreme speeds. He generally travels by jumping as described above though. The hulk is also highly resistant to damage, being near impervious to most forms of damage. Very little has been known to faze the Hulk, except those of the same power level as the Hulk such as The Thing, Thor, Abomination, and others.", image:"/hulk.jpg"}
 ]

 const list = () => {
     return [...data]
 };

 const find = (id) => {
     const post = data.find(post => post.id === +id);
     return {...post};
 }

 module.exports = {list: list, find: find};